# Generated by Django 5.0.6 on 2024-06-29 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_transaction_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='name',
            new_name='name_en',
        ),
        migrations.AddField(
            model_name='currency',
            name='code',
            field=models.CharField(default='A', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='currency',
            name='name_es',
            field=models.CharField(default='A', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 14, 44, 45, 577345)),
        ),
    ]
