# Generated by Django 5.0.6 on 2024-06-29 18:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_name_currency_name_en_currency_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='name_en',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='name_es',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 29, 14, 46, 45, 464897)),
        ),
    ]
