# Generated by Django 5.0.6 on 2024-07-04 21:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_account_options_account_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='visible',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 4, 17, 8, 59, 249841)),
        ),
    ]
