# Generated by Django 5.0.6 on 2024-07-06 19:32

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_transaction_options_remove_moneytag_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneytag',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 6, 15, 32, 41, 899484)),
        ),
    ]
