# Generated by Django 5.0.6 on 2024-08-11 18:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_moneytag_account_alter_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='to_account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='exchange_rate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.exchangerate'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='opening_movement',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='moneytag',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts_money_tags', to='core.account'),
        ),
        migrations.AlterField(
            model_name='moneytag',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='moneytag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='money_tags', to='core.tag'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 11, 14, 57, 46, 605359)),
        ),
        migrations.DeleteModel(
            name='Fee',
        ),
    ]
