# Generated by Django 5.0.6 on 2024-08-11 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_transaction_to_account_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='opening_movement',
            new_name='opening',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 11, 15, 17, 14, 591977)),
        ),
    ]
