# Generated by Django 5.0.6 on 2024-12-14 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_maincurrency_user_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincurrency',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 14, 13, 39, 48, 512086)),
        ),
    ]
