# Generated by Django 5.0.6 on 2024-12-14 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_maincurrency_id_alter_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 14, 13, 40, 14, 280457)),
        ),
    ]
