# Generated by Django 5.0.6 on 2024-12-18 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_exchangerate_exchange_rate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='moneytag',
            options={'ordering': ('tag',)},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
