# Generated by Django 5.0.6 on 2024-12-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_exchangerate_date_alter_transaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='internal',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
