# Generated by Django 5.0.6 on 2024-12-29 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_transaction_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='money_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.moneytag'),
        ),
    ]
