# Generated by Django 5.0.6 on 2024-12-29 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_transaction_money_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tag'),
        ),
    ]
