# Generated by Django 5.0.6 on 2024-12-29 21:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_transaction_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='voucher',
            field=models.FileField(blank=True, null=True, upload_to='vouchers/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'png'])]),
        ),
    ]
