# Generated by Django 5.0.6 on 2024-12-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_transaction_voucher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicbalance',
            options={'ordering': ('-year', '-month')},
        ),
        migrations.RemoveField(
            model_name='historicbalance',
            name='date',
        ),
        migrations.AddField(
            model_name='historicbalance',
            name='month',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicbalance',
            name='year',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
