# Generated by Django 5.0.6 on 2025-05-17 14:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_historicbalance_options_alter_account_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='month_goal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.CreateModel(
            name='TagHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag_history', to='core.tag')),
            ],
            options={
                'ordering': ('-year', '-month'),
            },
        ),
    ]
