from reportlab.platypus import PageBreak, Paragraph, Spacer, SimpleDocTemplate
from reportlab.platypus import Table, TableStyle
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from io import BytesIO
import datetime
import calendar

from django.http import HttpResponse
from django.db.models import Sum, Q

from core.models import Transaction, HistoricBalance, Tag, MoneyTag, Account
from core.utils import convert_all, convert_all_transactions_amounts_to_main_currency_precisely, figures_size

def generate_report(request, elements, title, name='report'):
    def primera_pagina(canvas, doc):
        '''
        Resumen:
            Esta función coloca la disposición del encabezado del PDF a generar.
        '''
        width, height = A4
        canvas.saveState()
        titleStyle = ParagraphStyle(
            'title',
            fontSize=20,
            fontFamily='Junge',
            textTransform='uppercase',
            alignment=1,
            leading=24,
            color = colors.red
        )

        header = Paragraph(reportHeader, titleStyle)
        header.wrapOn(canvas, width-200, height+350)
        header.drawOn(canvas,100,765)

        footer = Paragraph(f'<p>Generated by the user {request.user.get_full_name()}. </p>')
        footer.wrapOn(canvas, width, height)
        footer.drawOn(canvas,40,745)

        time = Paragraph(date)
        time.wrapOn(canvas, width, height)
        time.drawOn(canvas,470,745)

        canvas.restoreState()

        canvas.saveState()
        canvas.setFont('Times-Roman', 10)
        page_number_text = "Page %d" % (doc.page)
        canvas.drawCentredString(
            4 * inch,
            0.3 * inch,
            page_number_text + ', ' + reportHeader + ', ' + date + '.'
        )
        canvas.restoreState()

    def footer(canvas, doc):
        '''
        Resumen:
            Esta función coloca la disposición del pie de página del PDF a generar.
        '''
        canvas.saveState()
        canvas.setFont('Times-Roman', 10)
        page_number_text = "Page %d" % (doc.page)
        canvas.drawCentredString(
            4 * inch,
            0.3 * inch,
            page_number_text + ', ' + reportHeader + ', ' + date + '.'
        )
        canvas.restoreState()

    reportHeader = title
    date = datetime.datetime.now().strftime('%d/%m/%Y - %H:%M:%S')
    buff = BytesIO()
    doc = SimpleDocTemplate(buff,pagesize=A4, topMargin=30, bottomMargin=30)
    story = []

    story = [
        Spacer(0, 1 * inch),
        *elements
    ]

    doc.build(story, 
        onFirstPage=primera_pagina,
        onLaterPages=footer,
    )
          
    response = HttpResponse(content_type='application/pdf')
    fecha = datetime.datetime.now()
    response['Content-Disposition'] = f'attachment; filename="{name}_{fecha.year}_{fecha.month}_{fecha.day}_{fecha.hour}_{fecha.minute}.pdf"'

    response.write(buff.getvalue())
    buff.close()

    return response

def generate_monthly_transactions_report(request, account, month, year):
    '''
    Resumen:
        Esta función genera un reporte PDF de las transacciones mensuales.
    '''
    currency = account.currency.code
    main_currency = request.user.main_currency

    table_transactions = [
        ['Date', 'Description', 'Tag', f'Income ({currency})', f'Expense ({currency})', f'Balance ({currency})'],
    ]

    table_tags = [
        ['Tag', f'Income ({currency} / {main_currency})', f'Expense ({currency} / {main_currency})'],
    ]

    table_summary = [
        ['Concept', f'Value ({currency} / {main_currency})'],
    ]
    
    if year and month:
        previous_month = int(month) - 1 if int(month) > 1 else 12
        previous_year = int(year) - 1 if int(month) == 1 else year
        start_balance = HistoricBalance.objects.filter(
            year=previous_year,
            month=previous_month,
            account=account
        ).first()

        transactions = Transaction.objects.filter(
            date__year=year,
            date__month=month,
            from_account=account,
            hold=False,
        ).order_by('date')

        if start_balance:
            start_balance = start_balance.balance
            table_transactions.append([
                f'{year}-{month if int(month) > 9 else "0" + str(month)}-01',
                'Start Balance',
                '',
                f'{start_balance:,.2f}' if start_balance > 0 else '',
                '',
                f'{start_balance:,.2f}'
            ])
        else:
            start_balance = 0

        tags = {}
        sums = {
            'in_int': 0,
            'out_int': 0,
            'in_ex': 0,
            'out_ex': 0,
            'in_mc': 0,
            'out_mc': 0,
            'in_ex_mc': 0,
            'out_ex_mc': 0,
            'cash_flow': 0,
            'cash_flow_mc': 0,
            'avg_balance': 0,
            'avg_balance_mc': 0,
        }
        current_balance = start_balance

        import calendar
        _, num_days = calendar.monthrange(int(year), int(month))

        for i in range(1, num_days + 1):
            transactions_day = transactions.filter(date__day=i)
            day = datetime.datetime(int(year), int(month), i)

            for transaction in transactions_day:
                current_balance += transaction.amount if transaction.transaction_type == '+' else -transaction.amount
           
                table_transactions.append([
                    Paragraph(transaction.date.strftime('%Y-%m-%d %H:%M')),
                    Paragraph((transaction.description if transaction.description else '-') + " " + (f"[I]" if transaction.internal else '[E]')),
                    Paragraph(transaction.tag.name if transaction.tag else '-'),
                    Paragraph(f'{transaction.amount:,.2f}') if transaction.transaction_type == '+' else '',
                    Paragraph(f'{abs(transaction.amount):,.2f}') if transaction.transaction_type == '-' else '',
                    Paragraph(f'{current_balance:,.2f}'),
                ])

                sums['in_int'] += transaction.amount if transaction.transaction_type == '+' and transaction.internal else 0
                sums['out_int'] += abs(transaction.amount) if transaction.transaction_type == '-' and transaction.internal else 0
                sums['in_ex'] += transaction.amount if transaction.transaction_type == '+' and not transaction.internal else 0
                sums['out_ex'] += abs(transaction.amount) if transaction.transaction_type == '-' and not transaction.internal else 0
                sums['in_mc'] += convert_all_transactions_amounts_to_main_currency_precisely(
                    [{'amount': transaction.amount, 'from_account__currency': transaction.from_account.currency.pk, 'exchange_rate': transaction.exchange_rate.pk}], request.user.main_currency.pk
                ) if transaction.transaction_type == '+' and transaction.internal else 0
                sums['out_mc'] += convert_all_transactions_amounts_to_main_currency_precisely(
                    [{'amount': transaction.amount, 'from_account__currency': transaction.from_account.currency.pk, 'exchange_rate': transaction.exchange_rate.pk}], request.user.main_currency.pk
                ) if transaction.transaction_type == '-' and transaction.internal else 0
                sums['in_ex_mc'] += convert_all_transactions_amounts_to_main_currency_precisely(
                    [{'amount': transaction.amount, 'from_account__currency': transaction.from_account.currency.pk, 'exchange_rate': transaction.exchange_rate.pk}], request.user.main_currency.pk
                ) if transaction.transaction_type == '+' and not transaction.internal else 0
                sums['out_ex_mc'] += convert_all_transactions_amounts_to_main_currency_precisely(
                    [{'amount': transaction.amount, 'from_account__currency': transaction.from_account.currency.pk, 'exchange_rate': transaction.exchange_rate.pk}], request.user.main_currency.pk
                ) if transaction.transaction_type == '-' and not transaction.internal else 0
                
                if transaction.tag:
                    if transaction.tag.name not in tags:
                        tags[transaction.tag.name] = {
                            'in': 0,
                            'out': 0,
                            'in_mc': 0,
                            'out_mc': 0,
                        }
                    if transaction.transaction_type == '+':
                        tags[transaction.tag.name]['in'] += transaction.amount
                        tags[transaction.tag.name]['in_mc'] += convert_all_transactions_amounts_to_main_currency_precisely(
                            [{'amount': transaction.amount, 'from_account__currency': transaction.from_account.currency.pk, 'exchange_rate': transaction.exchange_rate.pk}], request.user.main_currency.pk
                        )
                    else:
                        tags[transaction.tag.name]['out'] += abs(transaction.amount)
                        tags[transaction.tag.name]['out_mc'] += convert_all_transactions_amounts_to_main_currency_precisely(
                        [{'amount': transaction.amount, 'from_account__currency': transaction.from_account.currency.pk, 'exchange_rate': transaction.exchange_rate.pk}], request.user.main_currency.pk
                        )   

            sums['avg_balance'] += current_balance
            sums['avg_balance_mc'] += convert_all_transactions_amounts_to_main_currency_precisely(
                [{'amount': current_balance, 'from_account__currency': account.currency.pk,  'date': day, 'exchange_rate': None}], request.user.main_currency.pk
            )

        sums['cash_flow'] = current_balance - start_balance
        sums['cash_flow_mc'] = sums['in_ex_mc'] + sums['in_mc'] - sums['out_ex_mc'] - sums['out_mc']

        sums['avg_balance'] = sums['avg_balance'] / num_days
        sums['avg_balance_mc'] = sums['avg_balance_mc'] / num_days

        table_tags += [
            [tag, f'{values["in"]:,.2f} / {values["in_mc"]:,.2f}', f'{values["out"]:,.2f} / {values["out_mc"]:,.2f}']
            for tag, values in tags.items()
        ]

        table_summary += [
            ['Total Income (Internal)', f'{sums["in_int"]:,.2f} / {abs(sums["in_mc"]):,.2f}'],
            ['Total Income (External)', f'{sums["in_ex"]:,.2f} / {abs(sums["in_ex_mc"]):,.2f}'],
            ['Total Expense (Internal)', f'{sums["out_int"]:,.2f} / {abs(sums["out_mc"]):,.2f}'],
            ['Total Expense (External)', f'{sums["out_ex"]:,.2f} / {abs(sums["out_ex_mc"]):,.2f}'],
            ['Cash Flow', f'{sums["cash_flow"]:,.2f} / {sums["cash_flow_mc"]:,.2f}'],
            ['Average Balance', f'{sums["avg_balance"] :,.2f} / {sums["avg_balance_mc"]:,.2f}'],
            ['Avg. Figures', f'{figures_size(sums["avg_balance"])}'],
            [f'Avg. Figures ({main_currency})', f'{figures_size(sums["avg_balance_mc"])}'],
        ]

        return generate_report(
            request,
            title=f'Monthly Transaction Report - {account.name} - {month}/{year}',
            elements=[
                Table(table_transactions, colWidths=(1*inch, 2.5*inch, 1*inch, 1*inch, 1*inch, 1*inch), style=[
                    ('BACKGROUND', (0, 0), (-1, 0), '#DDDDDD'),
                    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('GRID', (0, 0), (-1, -1), 1, '#000000'),
                ]),
                Spacer(0, 0.1 * inch),
                Table(table_tags, style=[
                    ('BACKGROUND', (0, 0), (-1, 0), '#DDDDDD'),
                    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('GRID', (0, 0), (-1, -1), 1, '#000000'),
                ]) if tags else Paragraph('No tags found for this month.'),
                Spacer(0, 0.1 * inch),
                Table(table_summary, style=[
                    ('BACKGROUND', (0, 0), (-1, 0), '#DDDDDD'),
                    ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                    ('GRID', (0, 0), (-1, -1), 1, '#000000'),
                ]),
            ],
            name=f'monthly_transactions_report',
        )
    
def generate_yearly_transactions_report(request, account, year):
    """
    Generates a PDF report for all the transactions in a year.
    """
    transactions = Transaction.objects.filter(
        from_account=account,
        date__year=year,
    ).order_by('date')
    main_currency = request.user.main_currency.currency

    sums = {
        'in_int': 0,
        'in_ex': 0,
        'in_mc': 0,
        'in_mc_ex': 0,
        'out_int': 0,
        'out_ex': 0,
        'out_mc': 0,
        'out_mc_ex': 0,
        'cash_flow': 0,
        'cash_flow_mc': 0,
        'avg_balance': 0,
        'avg_balance_mc': 0,
    }

    tag_totals = {}

    first_day = transactions.order_by('date').first().date.date()
    last_day = datetime.date.today()
    num_days = (last_day - first_day).days + 1
    current_balance = HistoricBalance.objects.filter(
        account=account,
        year=int(year)-1,
        month=12,
    ).first().balance if HistoricBalance.objects.filter(
        account=account,
        year=int(year)-1,
        month=12,
    ).exists() else account.start_balance

    for day in range(num_days):
        daily_transactions = transactions.filter(date__year=year, date__month=(first_day + datetime.timedelta(days=day)).month, date__day=(first_day + datetime.timedelta(days=day)).day)
        
        for transaction in daily_transactions:
            if transaction.transaction_type == '+':
                if transaction.internal:
                    sums['in_int'] += transaction.amount
                    sums['in_mc'] += convert_all_transactions_amounts_to_main_currency_precisely(
                        [{'amount': transaction.amount, 'from_account__currency': transaction.from_account.currency.pk, 'exchange_rate': transaction.exchange_rate.pk if transaction.exchange_rate else None, 'date': transaction.date.date()}], main_currency.pk
                    )
                else:
                    sums['in_ex'] += transaction.amount
                    sums['in_mc_ex'] += convert_all_transactions_amounts_to_main_currency_precisely(
                        [{'amount': transaction.amount, 'from_account__currency': transaction.from_account.currency.pk, 'exchange_rate': transaction.exchange_rate.pk if transaction.exchange_rate else None, 'date': transaction.date.date()}], main_currency.pk
                    )
            else:
                if transaction.internal:
                    sums['out_int'] += abs(transaction.amount)
                    sums['out_mc'] += convert_all_transactions_amounts_to_main_currency_precisely(
                        [{'amount': transaction.amount, 'from_account__currency': transaction.from_account.currency.pk, 'exchange_rate': transaction.exchange_rate.pk if transaction.exchange_rate else None, 'date': transaction.date.date()}], main_currency.pk
                    )
                else:
                    sums['out_ex'] += abs(transaction.amount)
                    sums['out_mc_ex'] += convert_all_transactions_amounts_to_main_currency_precisely(
                        [{'amount': transaction.amount, 'from_account__currency': transaction.from_account.currency.pk, 'exchange_rate': transaction.exchange_rate.pk if transaction.exchange_rate else None, 'date': transaction.date.date()}], main_currency.pk
                    )
            current_balance += transaction.amount
        
            if transaction.tag:
                if transaction.transaction_type == '-' and not transaction.internal:
                    if transaction.tag.name in tag_totals:
                        tag_totals[transaction.tag.name]['amount'] += transaction.amount
                        tag_totals[transaction.tag.name]['mc'] += convert_all_transactions_amounts_to_main_currency_precisely(
                            [{
                                'amount': transaction.amount,
                                'from_account__currency': transaction.from_account.currency.pk,
                                'exchange_rate': transaction.exchange_rate.pk if transaction.exchange_rate else None,
                                'date': transaction.date
                            }], main_currency.pk
                        )
                    else:
                        tag_totals[transaction.tag.name] = {
                            'amount': transaction.amount,
                            'mc': convert_all_transactions_amounts_to_main_currency_precisely(
                                [{
                                    'amount': transaction.amount,
                                    'from_account__currency': transaction.from_account.currency.pk,
                                    'exchange_rate': transaction.exchange_rate.pk if transaction.exchange_rate else None,
                                    'date': transaction.date
                                }], main_currency.pk
                            )
                        }

        sums['avg_balance'] += current_balance
        sums['avg_balance_mc'] += convert_all_transactions_amounts_to_main_currency_precisely(
            [{'amount': current_balance, 'from_account__currency': account.currency.pk, 'date': first_day + datetime.timedelta(days=day), 'exchange_rate': None}], main_currency.pk
        )

    # Calculate cash flow and average balance
    sums['cash_flow'] = sums['in_int'] + sums['in_ex'] - sums['out_int'] - sums['out_ex']
    sums['cash_flow_mc'] = sums['in_mc'] + sums['in_mc_ex'] - sums['out_mc'] - sums['out_mc_ex']
    sums['avg_balance'] /= num_days
    sums['avg_balance_mc'] /= num_days

    # Create a table for transactions with IN, OUT, and BALANCE for each month
    months = HistoricBalance.MONTHS
    table_months = []
    for month, name in months:
        month_transactions = transactions.filter(date__month=month)
        month_balance = HistoricBalance.objects.filter(account=account, month=month, year=year).first()
        if month_balance is None:
            month_balance = 0
        else:
            month_balance = month_balance.balance
        
        in_sum = month_transactions.filter(transaction_type="+").aggregate(Sum("amount"))["amount__sum"] or 0
        out_sum = abs(month_transactions.filter(transaction_type="-").aggregate(Sum("amount"))["amount__sum"] or 0)
        
        table_months.append([
            name,
            f'{in_sum:,.2f}' if month <= datetime.date.today().month else '-',
            f'{out_sum:,.2f}' if month <= datetime.date.today().month else '-',
            f'{month_balance:,.2f}' if month <= datetime.date.today().month else '-',
        ])

    table_months = Table(
        [
            ['Month', f'Income ({account.currency.code})', f'Expense ({account.currency.code})', f'Balance ({account.currency.code})'],
            *table_months
        ],
        style=[
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 0), (-1, -1), 8),
            ('LINEBELOW', (0, 0), (-1, 0), 1, colors.black),
            ('LINEBELOW', (0, 1), (-1, -1), 0.5, colors.gray),
        ],
    )

    table_tags = [
        ['Tag', f'Total Spent ({account.currency.code})', f'Total Spent ({main_currency.code})'],
    ]
    for tag, total in tag_totals.items():
        table_tags.append([
            tag,
            f"{abs(total['amount']):,.2f}",
            f"{abs(total['mc']):,.2f}",
        ])

    table_summary = [
        ["Concept", f'Value ({account.currency.code} / {main_currency.code})'],
        ['Total Internal Income', f'{sums["in_int"]:,.2f} / {abs(sums["in_mc"]):,.2f}'],
        ['Total External Income', f'{sums["in_ex"]:,.2f} / {abs(sums["in_mc_ex"]):,.2f}'],
        ['Total Internal Expenses', f'{sums["out_int"]:,.2f} / {abs(sums["out_mc"]):,.2f}'],
        ['Total External Expenses', f'{sums["out_ex"]:,.2f} / {abs(sums["out_mc_ex"]):,.2f}'],
        ['Cash Flow', f'{sums["cash_flow"]:,.2f} / {sums["cash_flow_mc"]:,.2f}'],
        ['Average Balance', f'{sums["avg_balance"]:,.2f} / {sums["avg_balance_mc"]:,.2f}'],
        ['Avg. Figures', f'{figures_size(sums["avg_balance"])}'],
        [f'Avg. Figures ({main_currency.code})', f'{figures_size(sums["avg_balance_mc"])}'],
    ]

    return generate_report(
        request,
        title=f'Yearly Transactions Report for {account} ({year})',
        elements=[
            table_months,
            Spacer(1, 5),
            Table(
                table_tags,
                style=[
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                    ('FONTSIZE', (0, 0), (-1, -1), 8),
                    ('LINEBELOW', (0, 0), (-1, 0), 1, colors.black),
                    ('LINEBELOW', (0, 1), (-1, -1), 0.5, colors.gray),
                ],
            ),
            Spacer(1, 5),
            Table(
                table_summary,
                style=[
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                    ('FONTSIZE', (0, 0), (-1, -1), 8),
                    ('LINEBELOW', (0, 0), (-1, 0), 1, colors.black),
                    ('LINEBELOW', (0, 1), (-1, -1), 0.5, colors.gray),
                ],
            ),
        ],
        name=f'yearly_transactions_report',
    )

def generate_current_tags_report(request):
    tags = Tag.objects.filter(user=request.user).select_related('user')
    main_currency = request.user.main_currency.currency
    table_tags = [
        ["Tag", f'Total ({main_currency.code})'],
    ]
    total_assigned_main_currency = 0

    for tag in tags:
        total_assigned_by_currency = MoneyTag.objects.filter(tag=tag).values('account__currency').annotate(total=Sum('amount')).order_by('account__currency')
        total_assigned = []
        for currency in total_assigned_by_currency:
            total_assigned.append({
                'currency': currency['account__currency'],
                'total': currency['total'],
            })

        total_assigned = convert_all(
            total_assigned,
            main_currency.pk,
        )

        total_assigned_main_currency += total_assigned
        
        table_tags.append([
            tag.name,
            f'{total_assigned:,.2f}',
        ])

    total_balance_main_currency = sum(
        convert_all(
            [{'total': account.current_balance, 'currency': account.currency.pk}],
            main_currency.pk
        )
        for account in Account.objects.filter(owner=request.user, visible=True)
    )

    table_tags.append([
        'Total Balance (All Accounts)',
        f'{total_balance_main_currency:,.2f}',
    ])

    table_tags.append([
        'Total Assigned Money',
        f'{total_assigned_main_currency:,.2f}',
    ])

    table_tags.append([
        'Total Unassigned Money',
        f'{total_balance_main_currency - total_assigned_main_currency:,.2f}',
    ])

    return generate_report(
        request,
        title='Current Transactions Report for Tags',
        elements=[
            Table(
                table_tags,
                style=[
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                    ('FONTSIZE', (0, 0), (-1, -1), 8),
                    ('LINEBELOW', (0, 0), (-1, 0), 1, colors.black),
                    ('LINEBELOW', (0, 1), (-1, -1), 0.5, colors.gray),
                ],
            ),
        ],
        name='current_tags_report',
    )

def generate_monthly_transactions_report_all_accounts(request, year, month):
    """
    Generates a PDF report for all the transactions in a month as a summary.
    """
    total_balance_main_currency = 0
    total_start_balance = 0
    main_currency = request.user.main_currency.currency
    year = int(year)
    month = int(month)
    
    table_accounts = [
        ['Account', 'Start Balance', f'In Ext.', 'In Int.', 'Out Ext.', 'Out Int.', 'End Balance'],
    ]
    table_dict = {}
    table_tags = {}
    for account in Account.objects.filter(visible=True, owner=request.user):
        print(account)
        table_dict[account] = {
            'in_ext': 0,
            'in_int': 0,
            'out_ext': 0,
            'out_int': 0,
        }

        
        if int(year) >= account.opening_time.year:
            start_balance = HistoricBalance.objects.filter(
                year=year if month > 1 else year - 1,
                month=month - 1 if month > 1 else 12,
                account=account
            ).first().balance if HistoricBalance.objects.filter(
                year=year if month > 1 else year - 1,
                month=month - 1 if month > 1 else 12,
                account=account
            ).exists() else 0
        elif(account.opening_time.year == int(year) and int(month) >= account.opening_time.month):
            start_balance = account.start_balance
        else:
            start_balance = 0

        start_balance = convert_all_transactions_amounts_to_main_currency_precisely(
            [{'amount': start_balance, 'from_account__currency': account.currency.pk, 'exchange_rate': None, 'date': datetime.date(int(year), int(month), 1)}], main_currency.pk
        )
        total_start_balance += start_balance

        for transaction in Transaction.objects.filter(
            from_account=account,
            date__year=year,
            date__month=month,
        ):
            converted_amount = convert_all_transactions_amounts_to_main_currency_precisely(
                [{'amount': transaction.amount, 'from_account__currency': account.currency.pk, 'exchange_rate': transaction.exchange_rate.pk if transaction.exchange_rate else None, 'date': transaction.date.date()}], main_currency.pk
            )
            if transaction.transaction_type == '+':
                if transaction.internal:
                    table_dict[account]['in_int'] += converted_amount
                else:
                    table_dict[account]['in_ext'] += converted_amount
            else:
                if transaction.internal:
                    table_dict[account]['out_int'] += converted_amount
                else:
                    table_dict[account]['out_ext'] += converted_amount

            if(transaction.tag):
                if transaction.tag.name not in table_tags:
                    table_tags[transaction.tag.name] = {
                        'in': 0,
                        'out': 0
                    }

                if transaction.transaction_type == '+' and not transaction.internal:
                    table_tags[transaction.tag.name]['in'] += converted_amount
                elif transaction.transaction_type == '-' and not transaction.internal:
                    table_tags[transaction.tag.name]['out'] += converted_amount

        final_balance_record = HistoricBalance.objects.filter(
            year=year,
            month=month,
            account=account
        ).first().balance if HistoricBalance.objects.filter(
            year=year,
            month=month,
            account=account
        ).exists() else 0
        table_dict[account]['final_balance'] = convert_all_transactions_amounts_to_main_currency_precisely(
            [{'amount': final_balance_record, 'from_account__currency': account.currency.pk, 'exchange_rate': None, 'date': datetime.date(year, month, calendar.monthrange(year, month)[1])}], main_currency.pk
        )

        total_balance_main_currency += table_dict[account]['final_balance']
        
        table_accounts.append([
            account.name,
            f'{start_balance:,.2f}',
            f'{table_dict[account]["in_ext"]:,.2f}',
            f'{table_dict[account]["in_int"]:,.2f}',
            f'{table_dict[account]["out_ext"]:,.2f}',
            f'{table_dict[account]["out_int"]:,.2f}',
            f'{table_dict[account]["final_balance"]:,.2f}',
        ])

    exchange_in = 0
    exchange_out = 0
    for transaction in Transaction.objects.filter(
        date__year=year,
        date__month=month,
        from_account=None
    ):
        if(transaction.transaction_type == '+'):
            exchange_in += transaction.amount
        else:
            exchange_out += transaction.amount
    
    table_accounts.append([
        'EXCHANGE RATE DIFFERENCES',
        '-',
        f'{exchange_in:,.2f}',
        '-',
        f'{abs(exchange_out):,.2f}',
        '-',
        '-',
    ])

    # second table: tags
    table_tags_summary = [
        ['Tag', 'IN', 'OUT'],
        *([tag, f'{values["in"]:,.2f}', f'{abs(values["out"]):,.2f}'] for tag, values in table_tags.items())
    ]
    
    # third table
    table_summary = [
        ['Concept', 'Value'],
    ]
    table_summary.append([
        'Total Start Balance',
        f'{total_start_balance:,.2f}',
    ])
    table_summary.append([
        'Total Final Balance',
        f'{total_balance_main_currency:,.2f}',
    ])
    table_summary.append([
        '% of Variation (Balances)',
        f'{((total_balance_main_currency - total_start_balance) / total_start_balance) * 100:,.2f}%',
    ])
    table_summary.append([
        'Total Ext. Expenses',
        f'{sum([values["out_ext"] for values in table_dict.values()]):,.2f}',
    ])
    table_summary.append([
        'Total Ext. Income',
        f'{sum([values["in_ext"] for values in table_dict.values()]):,.2f}',
    ])
    table_summary.append([
        'Total Cash Flow',
        f'{total_balance_main_currency - total_start_balance:,.2f}',
    ])
    
    return generate_report(
        request,
        title=f'Monthly Summary Report for All Accounts - {month}/{year}',
        elements=[
            Paragraph(f'All amounts are represented in {main_currency}', style=ParagraphStyle('normal', fontSize=10)),
            Table(
                table_accounts,
                style=[
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                    ('FONTSIZE', (0, 0), (-1, -1), 8),
                    ('LINEBELOW', (0, 0), (-1, 0), 1, colors.black),
                    ('LINEBELOW', (0, 1), (-1, -1), 0.5, colors.gray),
                ],
            ),
            Spacer(1, 10),
            Table(
                table_tags_summary,
                style=[
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                    ('FONTSIZE', (0, 0), (-1, -1), 8),
                    ('LINEBELOW', (0, 0), (-1, 0), 1, colors.black),
                    ('LINEBELOW', (0, 1), (-1, -1), 0.5, colors.gray),
                ],
            ),
            Spacer(1, 10),
            Table(
                table_summary,
                style=[
                    ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                    ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
                    ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
                    ('FONTSIZE', (0, 0), (-1, -1), 8),
                    ('LINEBELOW', (0, 0), (-1, 0), 1, colors.black),
                    ('LINEBELOW', (0, 1), (-1, -1), 0.5, colors.gray),
                ],
            ),
        ],
        name=f'monthly_transactions_report'
    )

def generate_yearly_transactions_report_all_accounts(request, account, year):
    """
    Generates a PDF report for all the transactions in a year.
    """
    pass